### ISSUE TITLE
Access to PITT Corpus

### ISSUE THREAD

**Issue by ghost** [ShreyanshJoshi/Alzheimers-Detection-by-Speech-Analysis#6]
Hello, this is Jang Kangwook, Ph.D candidate of electrical engieneering department, KAIST.

How can I get to the access of PITT Corpus?

And is DB free of charge?

Finally, what procedures I have to go through for the dataset?

Best regards

Kangwook

**Comment by ShreyanshJoshi** [comment]
Hey, actually we had mailed the requirement of such a dataset to our prof
(under whom we were working) who in turn had mailed the Dementia Bank
stating - "We would require audio datasets of patients and healthy
individuals to analyze whether a person shows signs of Dementia using
speech patterns".
Yes the DB is free of charge. No other procedure is required - they would
provide you credentials for the dataset (login/password).
